#!/usr/bin/env bash

####################################################################
# bl - BLACKLIST CHECK UNIX/LINUX UTILITY                          #
# copyright: (c) 2014 Anders Aarvik                                #
# author: Anders Aarvik (aarvik92@gmail.com) and contributors      #
# license: MIT licensed. See LICENSE                               #
# description: I was just a bit tired of web interfaces            #
####################################################################

# Adapted to use hetrixtools.com blacklists.

BLACKLIST="blists.txt"
FOUND=0


#### main ####
main() {

  [ $# -ne 1 ] && error "Please specify a FQDN or IP as a parameter."

  fqdn=$(echo $1 | grep -P "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")

  if [[ $fqdn ]] ; then

    echo "[MSG] Searching domain: $1 in blacklists..." | cecho YELLOW

    domain=$(host $1 | head -n1 | awk '{print $4}')

    reverseit $domain "[-] IP not valid or domain could not be resolved."
  else

    echo "[MSG] Searching IP: $1 in blacklists..." | cecho YELLOW
    reverseit $1 "IP not valid."
  fi

  loopthroughblacklists $1
}

#### reverseit ####
reverseit() {

  reverse=$(echo $1 |
    sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")

  if [ "x${reverse}" = "x" ] ; then

    error $2 
    exit 1
  fi
}

#### loopthroughblacklists ####
loopthroughblacklists() {

    reverse_dns=$(dig +short -x $1)

    for bl in $(cat $BLACKLIST) ; do

      listed=$(dig +timeout=1 +short -t a ${reverse}.${bl}.)

      if [[ $listed ]]; then

        if [[ $listed != *"timed out"* ]]; then
 
          echo "[-] $1 blacklisted by: $bl" | cecho LRED
          let FOUND=$FOUND+1
          
          if [[ $FOUND -gt 2 ]]; then            
            break
          fi
          
        fi
      fi

    done

    if [[ $FOUND -eq 0 ]]; then
      echo "[OK] $1 not blacklisted by lists in file $BLACKLIST." | cecho LGREEN
    else
      echo "[BL] $1 is blacklisted $FOUND or more times at hetrixtools.com" | cecho LRED
      echo "[URL] More info at: https://hetrixtools.com/blacklist-check/$1" | cecho BLUE
    fi
}

#### error ####
error() {

  echo $0 error: $1 >&2
  exit 2
}

#### cecho ####
cecho(){
  LGREEN="\033[1;32m"
  LRED="\033[1;31m"
  YELLOW="\033[1;33m"
  BLUE="\033[1;34m"
  NORMAL="\033[m"
 
  color=\$${1:-NORMAL}
 
  echo -ne "$(eval echo ${color})"
  cat
 
  echo -ne "${NORMAL}"
}

### initiate script ###
main $1
